### get requst
# @name lukeRespose
GET http://localhost:8081/user/isLoggedIn HTTP/1.1

### post request
POST http://localhost:8081/customer/one HTTP/1.1
content-type: application/json

{
    "firstName": "sample1",
    "lastName": "name"
}

###
POST http://localhost:8081/user/signup HTTP/1.1
content-type: application/json

{
    "firstName": "Lil3",
    "lastName": "Daw3",
    "email":"test3@yahoo.com",
    "about":"excelent student",
    "status": "active",
    "password":"123"
}

####
POST http://localhost:8081/user/signin HTTP/1.1
content-type: application/json

{
    "email":"test9@yahoo.com",
    "password":"123"
}

### post request
GET http://localhost:8081/customer/all HTTP/1.1
### post request
GET http://localhost:8081/user/isLoggedIn HTTP/1.1

###
POST http://localhost:8081/user/signup HTTP/1.1
content-type: application/json

{
    "firstName": "Lil3",
    "lastName": "Daw3",
    "email":"test9@yahoo.com",
    "password":"123",
    "phone": "51234343",
    "address": "123 main st",
    "role": "Captain"
}

###
GET http://localhost:8081/schedule HTTP/1.1

###
### post request
POST http://localhost:8081/schedule/one HTTP/1.1
content-type: application/json

{
    "name": "10am Shift", 
    "start": "2020-11-09", 
    "end": "2020-11-09", 
    "color": "primary",
    "email": "test924@yahoo.com"
}

###
### get request
GET http://localhost:8081/schedule/all HTTP/1.1